Repository SanaTameem/space-travelers-hub, pull requests merged in 2023-08, with the labels that each got.

#26 Create app and install basic dependencies - Setup
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .stylelintrc.json
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: Sana's task

#27 Create website header with empty nav - Setup
  public/index.html
  src/App.css
  src/App.js
  src/Assets/planet (1).png
  src/Styles/Header.css
  src/component/Dragons.jsx
  src/component/Header.jsx
  src/component/Missions.jsx
  src/component/Profile.jsx
  src/component/Rockets.jsx
  src/index.js
Labels: Chandan's task

#28 Structure myProfile page
  src/App.js
  src/Styles/Profile.css
  src/component/Profile.jsx
  src/components/Dragons.jsx
  src/components/Header.jsx
  src/components/Missions.jsx
  src/components/Profile.jsx
  src/components/Rockets.jsx
Labels: Peter's task

#29 Create basic structure for Rockets - Setup
  package-lock.json
  package.json
  src/Styles/Header.css
  src/Styles/Rockets.css
  src/components/Header.jsx
  src/components/Rockets.jsx
  src/index.js
  src/redux/rockets/rocketsSlice.js
  src/redux/store.js
Labels: Sana's task

#30 Add my dragons in the My profile section
  src/Styles/Profile.css
  src/components/Profile.jsx
Labels: Peter's task

#31 Add the structure of the missions
  src/Styles/Missions.css
  src/components/Missions.jsx
  src/redux/missions/missionsSlice.js
  src/redux/store.js
Labels: Peter's task

#32 Create basic structure for Dragons - Setup
  src/Styles/Dragons.css
  src/components/Dragons.jsx
  src/components/Missions.jsx
  src/redux/dragons/dragonsSlice.js
  src/redux/store.js
Labels: Chandan's task

#33 Feth Missions data from the API
  src/components/Missions.jsx
  src/redux/missions/missionsSlice.js
Labels: Peter's task

#34 Fetch rockets - Fetch data
  package-lock.json
  package.json
  src/components/Rockets.jsx
  src/redux/rockets/rocketsSlice.js
Labels: Sana's task

#35 Fetch dragons - Fetch data
  src/components/Dragons.jsx
  src/redux/dragons/dragonsSlice.js
Labels: Chandan's task

#37 Display dragons - Lists render
  src/components/Dragons.jsx
Labels: Chandan's task

#38 Display rockets - Lists render
  src/components/Dragons.jsx
  src/components/Rockets.jsx
Labels: Sana's task

#39 Implement rocket booking - Actions
  src/Styles/Rockets.css
  src/components/Rockets.jsx
  src/redux/rockets/rocketsSlice.js
Labels: Sana's task

#40 Implement dragon booking - Actions
  src/components/Dragons.jsx
  src/redux/dragons/dragonsSlice.js
Labels: Chandan's task

#41 Feature/impliment joining mission
  src/components/Missions.jsx
  src/redux/missions/missionsSlice.js
Labels: Peter's task

#42 Feature/mission leaving
  src/components/Missions.jsx
  src/redux/missions/missionsSlice.js
Labels: Peter's task

#43 Implement rocket booking cancelation - Actions
  src/components/Rockets.jsx
  src/redux/rockets/rocketsSlice.js
Labels: Sana's task

#44 Implement badge switching
  src/components/Missions.jsx
  src/redux/missions/missionsSlice.js
Labels: Peter's task

#46 Switch badges for Rockets - Conditional components
  src/components/Rockets.jsx
Labels: Sana's task

#47 Switch badges for Dragons - Conditional components
  src/components/Dragons.jsx
Labels: Chandan's task

#48 Display reserved rockets in My profile - Filters
  src/Styles/Profile.css
  src/components/Profile.jsx
  src/components/Rockets.jsx
  src/redux/rockets/rocketsSlice.js
Labels: Sana's task

#49 Display reserved dragons in My profile - Filter
  src/Styles/Profile.css
  src/components/Profile.jsx
  src/redux/dragons/dragonsSlice.js
Labels: Chandan's task

#50 Fixed errors
  src/components/Profile.jsx
Labels: Peter's task

#51 Test for Header, Profile and Rockets
  package.json
  src/tests/Header.test.js
  src/tests/Profile.test.js
  src/tests/RocketRender.test.js
  src/tests/Rockets.test.js
  src/tests/__snapshots__/Header.test.js.snap
  src/tests/__snapshots__/Profile.test.js.snap
  src/tests/__snapshots__/Rockets.test.js.snap
Labels: Sana's task

#52 Test for Dragons
  package-lock.json
  src/tests/DragonRender.test.js
  src/tests/Dragons.test.js
  src/tests/__snapshots__/Dragons.test.js.snap
Labels: Chandan's task

#53 Missions Test Feature
  package-lock.json
  package.json
  src/Styles/Profile.css
  src/components/Missions.jsx
  src/components/Profile.jsx
  src/redux/missions/missionsSlice.js
  src/tests/Missions.test.js
  src/tests/MissionsRender.test.js
  src/tests/__snapshots__/Missions.test.js.snap
Labels: Peter's task

#54 Feature/final touches
  MIT.md
  README.md
  package.json
  src/tests/DragonRender.test.js
  src/tests/RocketRender.test.js
  src/tests/__snapshots__/Profile.test.js.snap
Labels: Sana's task

#55 Update README.md file
  README.md
Labels: Sana's task
